import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const START=50;
const names=['Gaming Monitor','Mechanical Keyboard','Gaming Mouse','VR Headset','Tablet','Smart TV','Drone','Professional Camera','Gaming Laptop','Smartphone','Wireless Headphones','Streaming Microphone','Webcam','Portable Console','Projector','Smart Watch','Gaming Chair','Pool Table','Hot Tub','Home Theater','Swimming Pool','Garage','Dirt Bike','Motorcycle','Sports Car','Supercar','Limousine','Helicopter','Private Jet','Luxury Yacht','Skateboard','Mountain Bike','Electric Scooter','Arcade Machine','DJ Setup','Guitar','Drum Kit','Trophy','Luxury Car','Sports Yacht','Private Island','Luxury Mansion','Supercar Collection','Diamond Watch','Gold Statue','Rare Painting','Signed Jersey','Championship Trophy','Collector Card','Mystery Crate','Golden Controller','Limited Trophy','Gaming Desk','Race Simulator','Basketball','Football','Tennis Racket','Golf Set','Fishing Boat','Snowmobile','Jet Ski','Off-road Buggy','Cinema Room','Recording Studio','Music Studio','Rooftop Pool','Private Garage','Penthouse','Beach House','Mountain Cabin','Diamond Ring','Gold Chain','Emerald Necklace','Sapphire Watch','Platinum Bar','Crystal Crown','Golden Phone','Diamond Laptop','Retro Console','VR Racing Rig','Flight Simulator','Esports Booth','Streaming Room','Creator Camera Kit','Pro Drone','3D Printer'];
const cats=['All','Electronics','Gaming','Vehicles','Home','Luxury','Hobbies','Collectibles','Sports'];
const items=names.map((name,i)=>({id:i+1,name,price:Math.round((150+i*i*23)*10)/10,category:cats[1+i%8],rarity:['Common','Uncommon','Rare','Epic','Legendary','Mythic','Ultra Rare'][i%7]}));
const syms=['7','BAR','🍒','💎','⭐','🔔'];
function App(){
 const [logged,setLogged]=useState(localStorage.vc_logged==='1'),[user,setUser]=useState(localStorage.vc_user||''),[name,setName]=useState(''),[pass,setPass]=useState('');
 const [view,setView]=useState('home'),[more,setMore]=useState(false),[phone,setPhone]=useState(false),[admin,setAdmin]=useState(false);
 const [balance,setBalance]=useState(+localStorage.vc_balance||START),[inventory,setInventory]=useState(JSON.parse(localStorage.vc_inventory||'[]'));
 const [bet,setBet]=useState('1'),[percent,setPercent]=useState(false),[reels,setReels]=useState(['7','7','7']),[status,setStatus]=useState('Welcome to Vili Casino!');
 const [history,setHistory]=useState(JSON.parse(localStorage.vc_history||'[]')),[search,setSearch]=useState(''),[cat,setCat]=useState('All');
 const [jackpot,setJackpot]=useState(+localStorage.vc_jackpot||125430),[sounds,setSounds]=useState(true),[lang,setLang]=useState('English');
 useEffect(()=>localStorage.vc_balance=balance,[balance]);useEffect(()=>localStorage.vc_inventory=JSON.stringify(inventory),[inventory]);useEffect(()=>localStorage.vc_history=JSON.stringify(history),[history]);useEffect(()=>localStorage.vc_jackpot=jackpot,[jackpot]);
 const addLog=(type,amount,detail)=>setHistory(h=>[{time:new Date().toLocaleString(),type,amount,detail},...h].slice(0,100));
 const tone=()=>{if(!sounds)return;try{let A=window.AudioContext||window.webkitAudioContext,c=new A,o=c.createOscillator();o.connect(c.destination);o.start();o.stop(c.currentTime+.08)}catch{}};
 const spin=()=>{let a=+bet||0;if(percent)a=balance*a/100;if(a<=0||a>balance){setStatus('Invalid bet or insufficient balance.');return}setBalance(b=>b-a);let r=syms.map(()=>syms[Math.floor(Math.random()*syms.length)]);setReels(r);tone();let w=0;if(r[0]===r[1]&&r[1]===r[2])w=a*(r[0]==='7'?50:12);else if(r[0]===r[1]||r[1]===r[2]||r[0]===r[2])w=a*2;if(w){setBalance(b=>b+w);setStatus(`BIG WIN! +$${w.toFixed(2)}`);addLog('WIN',w,'Slot')}else{setStatus('No win this time.');addLog('SPIN',-a,'Slot')}};
 const buy=x=>{if(balance<x.price){setStatus('Not enough balance.');return}setBalance(b=>b-x.price);setInventory(i=>[...i,x]);addLog('PURCHASE',-x.price,x.name);setStatus(`${x.name} added to inventory.`);tone()};
 const filtered=useMemo(()=>items.filter(x=>(cat==='All'||x.category===cat)&&x.name.toLowerCase().includes(search.toLowerCase())),[search,cat]);
 const login=e=>{e.preventDefault();let n=name.trim()||'DemoPlayer';setUser(n);localStorage.vc_user=n;localStorage.vc_logged='1';setLogged(true)};
 if(!logged)return <div className="auth"><div className="authBox"><div className="brand big">VILI <span>CASINO</span></div><p>Virtual casino • virtual currency only</p><form onSubmit={login}><input placeholder="Username" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="Password" type="password" value={pass} onChange={e=>setPass(e.target.value)}/><button className="primary">PLAY!</button></form><small>New players start with $50.</small></div></div>;
 const apps=[['💬','Messages'],['👥','Friends'],['🎁','Gifts'],['💸','Send Money'],['🛒','Vili Market'],['🔨','Auctions'],['👤','Profile'],['🔔','Notifications'],['🏆','Achievements'],['📊','Stats'],['📰','News'],['🎰','Games'],['⚙️','Settings'],['🏦','Bank'],['₿','BTC Market'],['🎮','Mini Games']];
 return <div className="app"><header><div className="brand" onClick={()=>setView('home')}>VILI <span>CASINO</span></div><nav><button onClick={()=>setView('home')}>HOME</button><button onClick={()=>setView('slot')}>SLOT</button><button onClick={()=>setMore(!more)}>MORE</button><button onClick={()=>setView('market')}>MARKETPLACE</button><button onClick={()=>setView('leader')}>LEADERBOARD</button></nav><div className="head"><button onClick={()=>setPhone(true)}>📱</button><b>${balance.toFixed(2)}</b><button onClick={()=>setView('profile')}>👤</button><button onClick={()=>setAdmin(true)}>?</button></div></header>
 {more&&<div className="more">{['Blackjack','Wheel of Fortune','Coin Flip','Dice Game','Horse Race','Mines','Crash','Higher or Lower'].map(x=><button key={x} onClick={()=>{setStatus(`${x} module selected.`);setView('game');setMore(false)}}>{x}</button>)}</div>}
 <div className="announce">📢 Welcome to Vili Casino — Season 1 is live!</div><main>
 {view==='home'&&<section className="hero"><div><p className="eyebrow">SEASON 1</p><h1>VILI <span>CASINO</span></h1><p className="lead">Slots, collections, markets, virtual BTC, challenges and your own in-game phone.</p><div className="cards"><div><small>BALANCE</small><strong>${balance.toFixed(2)}</strong></div><div><small>ITEMS</small><strong>{inventory.length}</strong></div><div><small>JACKPOT</small><strong>${jackpot.toLocaleString()}</strong></div></div><div className="actions"><button className="primary" onClick={()=>setView('slot')}>PLAY SLOT</button><button onClick={()=>setView('market')}>MARKETPLACE</button><button onClick={()=>setPhone(true)}>📱 PHONE</button></div></div><aside><p className="eyebrow">DAILY BONUS</p><h2>+$100</h2><button className="primary" onClick={()=>{setBalance(b=>b+100);setStatus('Daily bonus claimed! +$100')}}>CLAIM BONUS</button></aside></section>}
 {view==='slot'&&<section className="panel"><div className="title"><div><p className="eyebrow">MAIN GAME</p><h2>Slot Machine Simulator</h2></div><button onClick={()=>setView('home')}>BACK</button></div><div className="reels">{reels.map((x,i)=><div className="reel" key={i}>{x}</div>)}</div><p className="status">{status}</p><div className="bet"><button className={percent?'active':''} onClick={()=>setPercent(!percent)}>%<small>{percent?'ON':'OFF'}</small></button><input type="number" value={bet} min="0" onChange={e=>setBet(e.target.value)}/><button className="primary spin" onClick={spin}>SPIN</button></div><div className="three"><div>🏆<b>JACKPOT</b><span>${jackpot.toLocaleString()}</span></div><div>🔥<b>BIG WIN</b><span>3 matching symbols</span></div><div>📜<b>HISTORY</b><span>{history.length} events</span></div></div></section>}
 {view==='market'&&<section className="panel"><div className="title"><div><p className="eyebrow">ADMIN-SUPPLIED SHOP</p><h2>Marketplace</h2></div><div className="filters"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search..."/><select value={cat} onChange={e=>setCat(e.target.value)}>{cats.map(c=><option key={c}>{c}</option>)}</select></div></div><div className="market">{filtered.map(x=><article className="item" key={x.id}><div className="art">{x.category==='Vehicles'?'🏎️':x.category==='Electronics'?'💻':x.category==='Luxury'?'💎':x.category==='Home'?'🏠':'🎮'}</div><span className="rarity">{x.rarity}</span><h3>{x.name}</h3><b>${x.price.toLocaleString()}</b><button className="primary" onClick={()=>buy(x)}>BUY</button></article>)}</div></section>}
 {view==='leader'&&<section className="panel"><p className="eyebrow">SEASON 1</p><h2>Leaderboards</h2><div className="list"><div>#1 Lucky Legend <b>$98,420</b></div><div>#2 Spin Master <b>$72,110</b></div><div>#3 Collector <b>$61,800</b></div><div className="you">YOUR RANK — tracked even outside Top 10</div></div></section>}
 {view==='profile'&&<section className="panel"><p className="eyebrow">PLAYER PROFILE</p><h2>{user}</h2><div className="profile"><div>💰 Balance <b>${balance.toFixed(2)}</b></div><div>📦 Items <b>{inventory.length}</b></div><div>🎰 Spins <b>{history.filter(x=>x.type==='SPIN').length}</b></div><div>🏆 Trophies <b>0</b></div></div><button onClick={()=>{localStorage.removeItem('vc_logged');setLogged(false)}}>LOG OUT</button></section>}
 {view==='history'&&<section className="panel"><h2>Game History</h2>{history.slice(0,30).map((x,i)=><div className="history" key={i}><b>{x.type}</b><span>{x.amount}</span><small>{x.detail} • {x.time}</small></div>)}</section>}
 {view==='settings'&&<section className="panel"><h2>Settings</h2><label>Language <select value={lang} onChange={e=>setLang(e.target.value)}>{['English','Suomi','Deutsch','Español','Français','Svenska','Norsk','Dansk','Português','Italiano','Nederlands'].map(x=><option key={x}>{x}</option>)}</select></label><label>Sounds <input type="checkbox" checked={sounds} onChange={e=>setSounds(e.target.checked)}/></label></section>}
 {view==='game'&&<section className="panel center"><div className="bigIcon">🎮</div><h2>{status}</h2><p>Mini-game module placeholder — all eight are reserved in the final feature list.</p></section>}
 </main><footer><span>Vili Casino • Virtual currency only</span><button onClick={()=>setView('history')}>HISTORY</button><button onClick={()=>setView('settings')}>⚙️</button><select value={lang} onChange={e=>setLang(e.target.value)}>{['English','Suomi','Deutsch','Español','Français','Svenska','Norsk','Dansk','Português','Italiano','Nederlands'].map(x=><option key={x}>{x}</option>)}</select></footer>
 {phone&&<div className="overlay" onClick={()=>setPhone(false)}><div className="phone" onClick={e=>e.stopPropagation()}><div className="phoneTop"><b>VILI</b><button onClick={()=>setPhone(false)}>×</button></div><div className="phoneBody"><div className="pbal">${balance.toFixed(2)}</div><div className="apps">{apps.map(([i,n])=><button key={n} onClick={()=>{setPhone(false);if(n==='Settings')setView('settings');else if(n==='Games'||n==='Mini Games')setView('game');else if(n==='Vili Market')setView('market');else setStatus(`${n} opened.`)}}><span>{i}</span><small>{n}</small></button>)}</div></div><div className="homebar"/></div></div>}
 {admin&&<div className="overlay"><div className="admin"><div className="title"><div><p className="eyebrow">SECURE AREA</p><h2>Admin Panel</h2></div><button onClick={()=>setAdmin(false)}>×</button></div><div className="adminGrid"><div>ONLINE<strong>1</strong></div><div>SHOP ITEMS<strong>{items.length}</strong></div><div>SPINS<strong>{history.length}</strong></div><div>JACKPOT<strong>${jackpot.toLocaleString()}</strong></div></div><div className="adminTools"><button onClick={()=>{setJackpot(250000);setAdmin(false)}}>SET JACKPOT $250K</button><button onClick={()=>{setBalance(b=>b+1000);addLog('ADMIN',1000,'Test grant');setAdmin(false)}}>TEST +$1000</button><button onClick={()=>{setStatus('GLOBAL EVENT: Bonus Weekend!');setAdmin(false)}}>GLOBAL EVENT</button><button onClick={()=>{setInventory([]);setAdmin(false)}}>WIPE DEMO INVENTORY</button></div><p>Production admin authorization belongs on the server; no secret is included in this client.</p></div></div>}
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
